services:
  - type: web
    name: aga-ini-restaurant
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
